### ISSUE TITLE
EasyDocumentEmbeddings with large text

### ISSUE THREAD

**Issue by mattivi** [Novetta/adaptnlp#59]
**Describe the bug**
I want to embed a long document and I am following the tutorial available here https://github.com/Novetta/adaptnlp/blob/master/tutorials/3.%20Embeddings/embeddings.ipynb.
It works up to a certain text lenght, e.g. about 300 tokens. After I get a CUDA error. How to embed long text? What's then best strategy?

**To Reproduce**

1. Go to ttps://github.com/Novetta/adaptnlp/blob/master/tutorials/3.%20Embeddings/embeddings.ipynb. and follow all steps there, with a much longer text.

1.1 Instantiate EasyDocumentEmbeddings :
```python
# Instantiate with a language model
from adaptnlp import EasyDocumentEmbeddings
embeddings = EasyDocumentEmbeddings("bert-base-cased")
```
1.2 Document Pool embedding
```python
example_text = "This is Albert.  My last name is Einstein.  I like physics and atoms.  \
Here is another sentence. And I will have many many more sentences..."

# Document Pool embedding
sentences = embeddings.embed_pool(example_text)
>> [Sentence: "This is Albert. My last name is Einstein. I like physics and atoms. Here is another sentence. And I will have many many more sentences..." - 25 Tokens]
```
The above provides only one flair Sentence object.

1.3 Get embeddings
```python
# Get the text/document embedding
for sentence in sentences:
    print(sentence)
    print(sentence.get_embedding().shape)
>> Sentence: "This is Albert. My last name is Einstein. I like physics and atoms. Here is another sentence. And I will have many many more sentences..." - 25 Tokens
torch.Size([3072])
```
The above works for documents with not many tokens. 
It will generate the following error for longer text:

2. Get error
```python
RuntimeError: CUDA error: device-side assert triggered
```

**Expected behavior**
Expect to have more than one sentence object and the entire document to be embedded.

**Desktop (please complete the following information):**
 - OS: Windows 10
-- python 3.6.10
-- adaptnlp '0.1.4'

**Additional context**
In the comments of this flair issue https://github.com/flairNLP/flair/issues/1323 I see that different sentences are provided to different Sentence objects:
```python
sentences = [Sentence("A Finnish sentence."), Sentence("Another one.")]

matrix = list()
for sentence in sentences:
    document_embeddings.embed(sentence)
    embedding = sentence.get_embedding()
    matrix.append(embedding)
```
Is this the best approach to embed long documents?
Should it be automatically taken into account in ```sentences = embeddings.embed_pool(example_text)``` ?

**Comment by aychang95** [comment]
Hi @mattivi!

If you are using a BERT-based model like `bert-base-cased` or any `roberta` models, you will unfortunately be limited to sequences of max length 512 sub-tokens (usually around 400-500 words depending on your tokenizer) for your text input.  This is due to the "limitations" in the model architecture which doesn't allow for dynamic size inputs.

Since the number of tokens depends on the tokenizer, a quick way to check whether your text has <512 sub-tokens is to run the following: 
```python
# transformers is a dependency for adaptnlp so this can be run immediately
from transformers import BertTokenizer
tokenizer=BertTokenizer.from_pretrained("bert-base-cased")
print(len(tokenizer.encode(example_text)))
```
Although, this may be a pain to always run or check :/

## Alternatives

### Using a Different Model
You can run models that do not have a sequence length limit for inputs like `xlnet-base-cased` or some of Flair's pre-trained models [here](https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/FLAIR_EMBEDDINGS.md).

Here's your example using an XLNet model that you can try out that works on very long sequences:

```python
# Instantiate with a different language model
from adaptnlp import EasyDocumentEmbeddings
embeddings = EasyDocumentEmbeddings("xlnet-base-cased")

example_text = "This is Albert.  My last name is Einstein.  I like physics and atoms.  \
Here is another sentence. And I will have many many more sentences..."

# Document Pool embedding
sentences = embeddings.embed_pool(text)

# Get the text/document embedding
for sentence in sentences:
    print(sentence)
    print(sentence.get_embedding().shape)
```

### If you really want to use BERT
This is more of a quick/naive method, but you could split your text into max lengths of 512 tokens and try to use that as your starting point.  I would suggest using overlapping chunks of your text instead of explicit partitions so that you can persist some of your contextual data between splits.

## Sentence Input/Output
`EasyDocumentEmbeddings.embed_pool()` will not split the string(s) inputs by periods, so one string will only produce one Sentence object.

The method takes in either one string, one `Sentence`, a list of `Sentence`s, or a list of strings, and it will always output a list of Sentence objects of length however many string/`Sentence`s you passed in through the `text` param.  It does not really matter whether you pass in a list of Sentence objects or a list of strings, though the former is technically slightly faster.

Hopefully that was helpful, and thank you for bringing up this issue!

**Comment by mattivi** [comment]
Thank you for clear and precise explanation! 
I tried xlnet-base-cased and it works fine until about 2500 words. I am using the quick/naive method of embedding overlapping chunks of text and then average them in order to embed the entire document.
